Human-Connection/Human-Connection

backend/src/graphql-schema.js, backend/src/middleware/permissionsMiddleware.js, backend/src/resolvers/rewards.js, backend/src/resolvers/rewards.spec.js, backend/src/schema.graphql
=> 204 tests for rewarding badges

deployment/human-connection/deployment-backend.yaml, deployment/human-connection/deployment-web.yaml, scripts/patch-deployment.yaml
The documentation clearly says:
```
Note: A Deployment’s rollout is triggered if and only if the
Deployment’s pod template (that is, .spec.template) is changed, for
example if the labels or container images of the template are updated.
Other updates, such as scaling the Deployment, do not trigger a
rollout.
```
Read: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment
=> Trigger rollout with a change to spec.template

backend/src/middleware/dateTimeMiddleware.js, backend/src/middleware/permissionsMiddleware.js, backend/src/resolvers/notifications.spec.js, backend/src/schema.graphql, backend/src/seed/factories/index.js, backend/src/seed/factories/notifications.js
Unfortunately it's not really possible to set default filters or default orderBy on the server. The client is responsible to set these attributes manually.
fixes #350
=> 350 query current users notifications

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
cc @ulfgebhardt
Unicode emojis are not displayed in my browser for all font sizes.
Except in the title of an issue or PR you can use `:emoji:` notation
to let Github render emojis. That's possible in commit messages as well
as the description of PRs/issues and in comments.
=> Use github emojis if possible

CONTRIBUTING.md, README.md
I changed the root of the docs URL at gitbook to https://docs.human-connection.org/human-connection/
=> Fix links to documentation

cypress/integration/common/report.js
At the moment, the most flaky cypress test is "ReportContent.feature" when it tries to click on the ContentMenu on the user profile.
```
Report and Moderate
✓ Report a post from various pages (example #1) (7462ms)
✓ Report a post from various pages (example #2) (6963ms)
1) Report user
✓ Review reported content (6731ms)
✓ Normal user can't see the moderation page (3142ms)
4 passing (35s)
1 failing
1) Report and Moderate Report user:
CypressError: Timed out retrying: cy.click() failed because this element is not visible:
<button class="ds-button content-menu-trigger ds-button-size-small ds-button-ghost">...</button>
This element '<button.ds-button.content-menu-trigger.ds-button-size-small.ds-button-ghost>' is not visible because it has an effective width and height of: '0 x 0' pixels.
Fix …
```
=> Try to fix flaky "ReportContent.feature"

deployment/legacy-migration/maintenance-worker/binaries/import_legacy_uploads
When downloading the current 72836 uploads from production, we run into bash's `argument list too long` error.
=> Prevent `argument list too long` error

webapp/pages/logout.vue
For any static image URL we don't need to use `<hc-image>`. The assets
will be served from the frontend container. I did not anticipate that we
have a lot of static images in the frontend when I said "You can replace
every image with the `<hc-image>` component".
@aonomike: In the future you can make some screenshots and post them in the PR
and ask for help.
@ulfgebhardt: Yes, it would have been safer not to merge the PR. We
might run into the danger of forgetting things like this.
=> Revert logout.vue

webapp/components/Empty.vue
This PR has been requested due to request from @roschaefer due to the discussion on [this PR](https://github.com/Human-Connection/Human-Connection/pull/614)
Reverts Empty.vue to use `<img>` tag instead of Image component
=> Refactor to use <img> instead of <hc-image> component for images

webapp/components/comments/CommentForm/index.vue, webapp/components/comments/CommentForm/spec.js, webapp/components/comments/CommentList/CommentList.spec.js, webapp/components/comments/CommentList/index.vue
- remove no-ssr, which was not necessary and causing the edit field not to appear the majority of the times visiting a Post.
- this was really bad user experience since a user would need to refresh the page to comment.
- removed args in refetchPostComments as there are no params passed in when it is called anymore
- needed to add an if statement since if there are no comments on a Post, then this.$apollo.queries.Post is undefined and it errors out trying to call refetch()
- update test to remove no-ssr
Co-authored-by: Mike Aono <aonomike@gmail.com>
- fixes #582
=> Fix edit field render bug(CommentForm)

.travis.yml, backend/package.json, webapp/package.json
I find it annoying to wait for code coverage tools to complete (~3
seconds) and especially to scroll up for every test run. So, this should
run coverage only on our build server *or* if you add `--coverage` on
the command line.
- None
=> Run coverage only if requested

deployment/legacy-migration/maintenance-worker/migration/neo4j/contributions.cql
@ulfgebhardt: I wondered about the list of tags after importing the
legacy db. It seems, each tag has at most 1 contribution. I guess it's
because we create a unique id for each tag, so two tags with the same
`name` e.g. `#hashtag` and `#hashtag` are not de-duplicated.
I'm currently sitting in the train and cannot run the data import myself, could
you double-check?
- None
=> Fix duplicate tags by using the name as the id

webapp/components/Editor/index.vue, webapp/components/LocaleSwitch.vue
- tiptap-extensions are not reactive
- we must call a method to change them dynamically
- emit changeLanguage event, which is listened for by the Editor component, which then calls a method to set the emptyNodeText of tiptap
- fixes #583
=> Fix placeholder text not translating bug

backend/src/middleware/index.js
@ulfgebhardt thank you for pointing out! That was a terrible bug.
@Mastercuber FYI: Activity Pub middleware was disabled on production. The RSA keys on staging must have been those that we seeded locally in development environment and dumped+uploaded to kubernetes.
- None
=> Don't remove middlewares in production

backend/package.json, backend/src/config/index.js, backend/src/middleware/index.js, backend/src/seed/reset-db.js
That way, we don't see verbose logging output on Travis. Setting DEBUG
will have the effect that all calls of `neo4jgraphql` will produce log
output.
- None
=> DISABLED_MIDDLEWARES only set outside production

backend/src/middleware/filterBubble/filterBubble.js, backend/src/middleware/filterBubble/filterBubble.spec.js, backend/src/middleware/filterBubble/replaceParams.js, backend/src/middleware/filterBubble/replaceParams.spec.js, backend/src/middleware/index.js, backend/src/schema/types/type/Post.gql
This is the backend part for #269. It can be merged independently.
With this PR the backend accepts an optional input parameter for `Post` query: It's called `filterBubble` and has currently two options: ~`{ author: followed }`~ `{ author: following }` or `{ author: all }`.
versus
I'm doing my best in the test setup to minimize those tests that do HTTP calls.
- None
=> 269 filter by followed users backend part

webapp/components/Editor/index.vue, webapp/components/comments/CommentList/index.vue
- fixes #804 
long-term we want to avoid these types of events, but in the short-term, or where necessary, we should be turning these off in a `beforeDestroy` lifecycle method
=> Turn off $root listeners in beforeDestroy

backend/package.json, backend/yarn.lock
After the relevant PR of mine has been merged, we should point our
`package.json` back to the published npm version of `neo4j-graphql-js`.
That way we are receiving updates again.
- None
=> Use upstream neo4j-graphql-js

backend/src/schema/resolvers/comments.js, backend/yarn.lock, webapp/components/comments/CommentForm/index.vue, webapp/components/comments/CommentForm/spec.js, webapp/components/comments/CommentList/CommentList.spec.js, webapp/components/comments/CommentList/index.vue, webapp/graphql/CommentMutations.js, webapp/graphql/PostCommentsQuery.js
- update apollo cache on successful mutation
- remove global event listener
- avoid refetch Post to update CommentsList
- return comment with its author from resolver
- fixes #900
=> Refactor CreateComments functionality

webapp/pages/index.vue
It annoys me that there are gaps for the 3 column layout, even if there
are more records left. So, the newsfeed layout has 1 column on mobile, 2
columns on tablet, and 3 columns on a desktop pc. So we should choose a
page size which is dividable by 1,2 and 3 that is 6. I have chosen 12
which is 2*6 to avoid clicking the reload posts button so often.
- None
=> Page size of 12 entries on / page

backend/src/middleware/nodes/locations.js
the problem is illustrated by the following example 
("Hamburg, Germany) and 
(Hamburg, Hamburg, Germany) 
to recognize.
In this case, Hamburg is created twice. 
There is a problem with the place.$ID and place.$place_type 
For capitals and large cities they have two place.$place_type (region,place) 
but the $ID is not region.$ID but place.ID. 
i changed this conflict. 
if a place.$place_type contains two specifications. 
the place.$ID is changed from "place" to "region". 
otherwise there can be conflicts in the DB like in the case of hamburg.
- fixes https://github.com/Human-Connection/Human-Connection/issues/850
=> region and place is no longer created twice.

webapp/components/Comment.vue
- fixes #717 
with deleted comments, they aren't the same height, but I can add `margin-bottom="large"` to the `<ds-space />`, but since there is just a single line, not sure if it looks better or not
=> Add basic styling for comment list

backend/src/schema/resolvers/reports.js, backend/src/schema/resolvers/reports.spec.js, backend/src/seed/factories/reports.js, webapp/components/ContentMenu.vue, webapp/components/Modal/ReportModal.vue, webapp/locales/de.json, webapp/locales/en.json, webapp/locales/fr.json
the one-time reporting of a user, post or comment 
is now possible. reporting is only possible once at a time. it returns a simple toast as error message. 
- fixes #https://github.com/Human-Connection/Human-Connection/issues/785
=> the one-time reporting of a user, post or comment 

backend/.env.template, deployment/human-connection/deployment-neo4j.yaml, deployment/human-connection/templates/configmap.template.yaml
Neo4j is looking for `NEO4J_USERNAME` and `NEO4J_PASSWORD` but not for `NEO4J_USER`.
- None
=> Neo4j uses a different name for its env vars

webapp/components/PostCard/index.vue
large images are also set to a maximum height of 300px on the overview page and centered vertically and horizontally
- fixes #https://github.com/Human-Connection/Human-Connection/issues/961
=> large images are set to maximum height

webapp/layouts/default.vue
I think I deleted the styling by using bot `:width` and `style`
property. I'm not quite sure if this resolves our problem. Anyways
I don't see a reason for having a right padding so I just removed it.
- None
=> Follow up of #958

backend/src/middleware/validation/validationMiddleware.js, backend/src/schema/resolvers/comments.js
- extract out the validations for a valid comment
- fixes #1037
=> Refactor CreateComment resolver

backend/src/middleware/email/templates/signup.js
Together with @victorrms2 I tried out the "Signup users as admin" feature and we ran into this.
- None
=> Bugfix: Signup email was missing email query param

docker-compose.travis.yml, docker-compose.yml, webapp/.gitignore, webapp/nuxt.config.js
NuxtJS wants to write into .nuxt. If the docker container writes into
.nuxt it will have the file permissions of the docker container user
even on the host system. So on the host system you cannot remove the
folder .nuxt anymore. This gets in the way of running NuxtJS on the host
system.
Now, host system and container will use different folder locations: `.nuxt` and `.nuxt-dist` respectively.
- None
=> Sledgehammer the file permission problem on docker

.codecov.yml, .travis.yml, backend/package.json, webapp/package.json
Recently, codecov was spamming our PRs with useless comments. I think this is the moment, when we could disable codecov comments without worrying. There is also reason for disabling the comments even if they would show a valid code coverage: People just get annoyed and start to turn off Github notifications.
- None
=> Silence codecov

webapp/pages/profile/_id/_slug.vue
The load more button depends on the total of the posts available.
Removing posts changes the total counts, so we have to manually update
it.
- fixes #822
=> Fix #822 by updating the counts of the user

deployment/volumes/neo4j-data.yaml
We had a beautiful error on https://nitro-production.human-connection.org/ because our 1GB persistent volume got full.
- None
=> Give more space to neo4j-data

webapp/pages/data-privacy.vue
EDIT:
```
Implement a German-only static data-privacy page
Okay, so the data privacy section needs to be updated @datenbrei:
We have two sections mentioning the Vimeo and Youtube plugins. After we
have the Embeds in place, we have many many more embedded code of 3rd
parties. Can we simply remove the two sections?
Also regarding the translations: I would wait until we have functional
components and we can write translations enriched by markup. Until then
I think it's sufficient to have German-only data privacy page.
```
=> Add static page for data privacy

webapp/components/Modal/ConfirmModal.spec.js, webapp/components/Modal/ReportModal.spec.js, webapp/components/PasswordReset/ChangePassword.spec.js, webapp/components/PasswordReset/Request.spec.js, webapp/components/Registration/CreateUserAccount.spec.js, webapp/components/Registration/Signup.spec.js
I tried out the maintainers suggestion @roschaefer, but it was throwing an error that it was unable to find the module, not sure if I need to build it as you suggested, but here is a `PR` to update the tests and favor the global registration of sweetalert-icons
- None
=> Stub sweetalert-icon in tests which use

webapp/Dockerfile, webapp/package.json, webapp/yarn.lock
The maintainers of https://github.com/arthurvasconcelos/vue-izitoast are
not extremely responsive, so I decided to point our package to my own
fork.
This makes the flag `--ignore-engines` obsolete.
- None
=> I had enough of `--ignore-engines`

webapp/components/CountTo.vue, webapp/pages/admin/index.vue
This commit message is a great example of why you should explain
**the reason** of your commit.
When I came across this bug I had a quick look into the code where it
came from. I could see that the bug only happened after a timer and
apparently reverting the biggest part of d84892930295dcfd3f6687fc33c7234446127099
would fix the bug. However I have no idea what the following commit
message means:
```
commit d84892930295dcfd3f6687fc33c7234446127099
Author: Grzegorz Leoniec <greg@app-interactive.de>
Date:   Wed Mar 6 18:45:57 2019 +0100
Improved countTo component
```
I just don't know why the code is there - like what is it's purpose
@appinteractive? I can only guess: I believe that it's supposed to
update the counters in-place (without starting from 0 everytime).
Because apollo was set to …
=> Fix `Cannot read property countUser of null`

webapp/components/CountTo.vue, webapp/components/User/index.vue, webapp/pages/admin/index.vue, webapp/pages/profile/_id/_slug.vue
If we always choose `0` as the default value for `endVal` in case it is
not given (maybe apollo assigns null when the request is in flight) then
just make `0` the default.
- None
=> Get rid of property warnings

deployment/human-connection/deployment-neo4j.yaml
Bug:
> apoc.cluster.graph is unavailable because it is sandboxed and has dependencies
> outside of the sandbox. Sandboxing is controlled by the
> dbms.security.procedures.unrestricted setting
See: https://stackoverflow.com/a/48773575
- None
=> Configure dbms.security.procedures

backend/src/jwt/encode.js, webapp/nuxt.config.js, webapp/store/auth.js
This won't fix the bug that can happen in `nuxtServerInit`. However,
according to the docs, we accepted JWT which was valid for 1000 days and
our cookie was valid for 3 days - completely weird.
See:
https://github.com/auth0/node-jsonwebtoken
https://github.com/nuxt-community/apollo-module
- None
=> Fix expiration dates of JWT and cookie

backend/package.json, backend/yarn.lock
I see a security vulnerability warning on Github. I hope that updating
transitive dependencies will silence the security warning.
I did `rm yarn.lock` followed by `yarn install`.
**EDIT**: OK, I found out what's causing the security warning. Running
```
yarn list lodash
├─ bitcore-lib@0.13.19
│  └─ lodash@3.10.1
└─ lodash@4.17.15
```
gives us the hint that the outdated lodash comes from `bitcore-lib`
which in turn is required by the extremely outdated `activitystrea.ms`
package. I tried to update it's dependencies in my fork without success.
If we ever touch the activity pub implementation we might have to
maintain this package ourselves.
FYI: @Mastercuber
=> Update transitive dependencies

backend/src/middleware/sentryMiddleware.js
I was wondering: Why don't we see AuthenticationErrors on Sentry? Why don't we have waay more spam? Await the incoming spam after this has been merged :wink: 
@datenbrei sb. deleted the user account with `admin` privileges on https://nitro-staging.human-connection.org/. On https://nitro-production.human-connection.org/ you can still log in with an admin account. The "cannot read property id of null" happens if there is an authentication error and sentry middleware is active.
@mattwr18 can you restore staging data please?
- None
=> Fix "cannot read property id of null" in staging

deployment/human-connection/deployment-neo4j.yaml
I cannot increase the memory above "2G" without getting an error that no
node has capacity for it. So I believe we have to change the kubernetes
cluster if we want to assign more memory to neo4j.
The other settings were suggested to me by [neo4j-admin memrec](https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin-memrec/).
- None
=> Add memory limits to neo4j deployment

cypress/README.md, docker-compose.override.yml
This should fix our endless debugging
@ogerly all you have to do now is to `docker-compose up`. On your host
machine, you can run `yarn run cypress:open` to run the tests.
- None
=> Simplify cypress testing on docker

deployment/digital-ocean/https/templates/ingress.template.yaml, deployment/legacy-migration/maintenance-worker/migration/mongo/.env
- allows the client to send files at least the size we agreed in the vue-dropzone
- we don't need such a small split size as we don't run it on the remote server
- fixes #1405
=> Increase nginx client max body size, split size legacy migration

backend/src/schema/resolvers/helpers/Resolver.js, backend/src/schema/resolvers/users.js, backend/src/schema/types/type/User.gql, deployment/legacy-migration/maintenance-worker/migration/neo4j/contributions/contributions.cql, webapp/pages/index.vue, webapp/pages/profile/_id/_slug.spec.js, webapp/pages/profile/_id/_slug.vue
Ok, so here are multiple issues:
1. In cypher, `NOT NULL` will return `NULL` not `FALSE`. If we want
`FALSE` to be set in the database import, we should use `COAELESCE`
to find the first not-null value.
See:
https://neo4j.com/docs/cypher-manual/current/syntax/working-with-null/
https://markhneedham.com/blog/2017/02/22/neo4j-null-values-even-work/
2. I removed the `disabled` and `deleted` checks on the commented
counter. With `neo4j-graphql-js` it is not possible to filter on the
join models (at least not without a lot of complexity) for disabled or
deleted items. Let's live with the fact that the list of commented posts
will include those posts, where the user has deleted his comment or where
the user's comment was disabled. It's being displayed as "not available"
so I think this is OK …
=> Fix database import, pagination and counters on user profile page

webapp/assets/styles/imports/_tooltip.scss, webapp/assets/styles/main.scss
This is a quick'n'dirty solution to disable background scrolling when a popover is open. You can test this by opening the notifications dropdown or filter menu.
- fixes #1413
=> Disable scrolling behind popover

webapp/assets/styles/main.scss, webapp/components/PostCard/index.vue, webapp/layouts/default.vue, webapp/pages/post/_id/_slug/index.vue, webapp/pages/profile/_id/_slug.vue
Uses hyphenation for
This solution does not work for all languages in all browsers on all operating systems (it's complicated :smirk:) – as a fallback words will still break in random places when they would otherwise overflow.
Setting hyphens to `auto` also means that _all_ words can potentially break, not just the very long ones overflowing the container. Unfortunately at this point this is a binary setting in CSS (can be either `on` or `off`) but there is a [property in planning](https://drafts.csswg.org/css-text-4/#hyphenate-char-limits) that would allow us to set a hyphenation threshold. I hope this will be implemented soon! Until then...
- fixes #1219
=> Use hyphens to separate words properly

webapp/pages/post/_id/_slug/more-info.vue
- use masonry grid for related posts
- fixes #1468
=> Fix related posts section in 'More Info'

webapp/components/Comment.spec.js, webapp/components/Comment.vue, webapp/components/CommentList/CommentList.spec.js
- fixes #1393 
this fixes the bug that the `show more` link is shown when a @mention occurs for comments that are shorter than 180 characters... 
at the moment, we were just checking if there is any difference between content and contentExcerpt, then showing the show more, but for some reason, there is always a difference between comments content longer or shorter than 180 characters
on my local development, the show less is still buggy, because it used the `content-viewer`, which used the editor, but in production it seems to not be an issue.
=> 1393 fix show less bugginess

webapp/pages/index.spec.js
- The test wasnt testing anything as the hashtag value was defaulting to null
- Fixed by setting value of hashtag to a string and then testing if the clearSearch works
=> Fix test by setting value of the mocked hashtag

.gitmodules, webapp/nuxt.config.js
Add styleguide/ as submodule
This should make new contributors aware that the Styleguide exists and
maybe maybe even encourage people to contribute to the Styleguide.
Also this enabled `yarn run dev:styleguide` to build the `webapp/` along
with the styleguide.
- None
=> Add styleguide as submodule

scripts/github_release.sh
I contributed to `ghr` here:
https://github.com/tcnksm/ghr/pull/118
Now after `ghr` does not need any artifacts to create a file, we can
stop uploading archives. (Use the default archives provided by Github)
- None
=> Relase without any artifacts

backend/src/models/User.js, backend/src/schema/resolvers/registration.spec.js
- add test case to test this use case since it is the default from our
UI
At the moment people cannot sign up unless they add their `About` property, which is not the desired functionality
=> Fix bug where about must not be empty string

scripts/docker_push.sh
The Dockerfile is still using `apk` instead of `apt-get` (Debian slim).
So that's why our build server never successfully pushed the
`maintenance-worker` image.
Building the docker image simply broke on that day and none of us noticed. Apparently nobody tried to do the backup from within the docker container.
- None
=> Exclude broken maintenance-worker docker image

webapp/components/CommentList/CommentList.vue
- add back class comments which adds spaces between comments
=> Fix styling issue in comments list

backend/src/schema/resolvers/notifications.spec.js
- the test was regularly failing our build
- change from toEqual to toMatchObject since there is more info coming
back, like errors, etc...
=> Fix intermittent failing test

webapp/components/CommentList/CommentList.spec.js, webapp/components/CommentList/CommentList.vue
- removes the sleep icon from the empty comments list
- uses `comments` from the translation files as title
- fixes #1659
=> Remove sleep icon from comments list

webapp/components/EmotionsButton/EmotionsButton.vue, webapp/locales/de.json, webapp/locales/en.json
Our dear @Hardy-Peaceglobal mentioned that when he had a look on the app
on my mobile.
**Before**
Maybe we can keep the translation for "Shouted" (I see it only once).
- None
=> Remove repetitive labels from emote button

webapp/components/Comment/Comment.vue, webapp/pages/post/_id/_slug/index.vue
- There was a bug that updates to comments were not being displayed
because of a v-show... https://vuejs.org/v2/guide/conditional.html#v-if-vs-v-show
Basically, what it says that is important for this bug is
"v-if...ensures that event listeners and child components inside the
conditional block are properly destroyed and re-created during toggles"
- Since we are using the editor to display comments in ContentViewer, we
need to set the min-height to 0px
- Co-authored-by: Alina Beck <alina.beck@mail.com>
- Co-authored-by: Robert Schäfer <git@roschaefer.de>
- fixes #1718
=> Fix bug UpdateComment, Fix styling on Comment

.vscode/settings.json
VSCode `editor.formatOnSave` seems sometimes to works against ESLint `eslint.autoFixOnSave`.
Please try out in your VSCode.
- None
=> 🍰 Try to fix VSCode format works against ESLint

backend/README.md, webapp/README.md
It makes much more sense to put it under the webapp's README than backend.
FYI: @mattwr18
- None
=> docs: moves storybook into webapp/README.md

backend/src/middleware/email/emailMiddleware.js
Set `ignoreTLS` option to true only when env variable `SMTP_IGNORE_TLS` is set to true.
Any other value will set the option to false.
- None
=> fix email middleware transport config

backend/package.json, backend/src/activitypub/ActivityPub.js, backend/src/activitypub/routes/inbox.js, backend/src/activitypub/routes/user.js, backend/src/activitypub/utils/activity.js, backend/src/middleware/activityPubMiddleware.js, backend/yarn.lock
We use an unmaintained package called `activitystrea.ms` for the
activity pub middleware. Since the activity pub middleware is dead code
at the moment I suggest that we remove that package and disable all the
code that depends on the package.
When we get back to implement the ActivityPub spec for Human Connection I
would suggest to maintain this package `activitystrea.ms`, update the
dependencies there and re-enable and **test** the code of the activity pub
middleware.
Here's the security warning:
- None
=> fix: Github's security vulnerability warning

backend/src/middleware/email/templates/emailVerification.html, backend/src/middleware/email/templates/layout.html, backend/src/middleware/email/templates/resetPassword.html, backend/src/middleware/email/templates/signup.html, backend/src/middleware/email/templates/wrongAccount.html
removes language toggle from email templates – turns out it's buggy in many webmail clients even with different fallback methods... :(
- fixes #1656
=> Remove language toggle from email template

webapp/pages/post/_id/_slug/index.vue
- we are currently enforcing a 1:1 max ratio on the root path and would
like to maintain consistency
=> Max aspect ratio of 1:1 for Post index page

backend/src/middleware/permissionsMiddleware.js, backend/src/middleware/permissionsMiddleware.spec.js, webapp/locales/de.json, webapp/locales/en.json, webapp/pages/admin/users.vue
- Display user email to administrators
- Refactor Permission middleware tests
- Add tests to check email of user only revealed to admin and owner
fixes #1704
=> Display user email for administrators

webapp/pages/admin/users.spec.js, webapp/pages/admin/users.vue
- fix #1645 
The only uppercase email address that we have is:
`wegenVersuchterScriptInjectionBlockiert@roschaefer.de`
:laughing: 
So, a year ago, I updated this email address manually to stop a user from logging in again.
=> fix: search for email case-insensitively

package.json, webapp/components/LocaleSwitch/LocaleSwitch.vue, webapp/components/RelativeDateTime/index.vue, webapp/locales/index.js, webapp/maintenance/source/nuxt.config.maintenance.js, webapp/nuxt.config.js, webapp/plugins/i18n.js, webapp/plugins/vue-filters.js, yarn.lock
While refactoring the login form component I found many inconsistent
ways of importing the list of locales. So I decided to refactor the
imports altogether. Don't use `process.env` to import locales!
- None
=> refactor: improve locale imports

backend/src/schema/resolvers/posts.js, backend/src/schema/resolvers/posts.spec.js, backend/src/schema/types/type/Post.gql, webapp/pages/index.vue, webapp/pages/profile/_id/_slug.vue
fix: performance issue with ordering
@mattwr18 @aonomike
You must never `ORDER BY` a property with a `@cypher` directive. Reason:
The order by performance will be terribly poor.
See my issue:
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/239
And my PR:
https://github.com/neo4j-graphql/neo4j-graphql-js/pull/247
- fixes #1997
=> 1997 fix performance issue with pinned post

webapp/Dockerfile.maintenance, webapp/components/LocaleSwitch/LocaleSwitch.spec.js, webapp/components/LocaleSwitch/LocaleSwitch.vue
~@ogerly the maintenance page needs just two components of the webapp
folder. For that reason we import only these. If you add imports to
`LocaleSwitch` component, you need to copy those files in the
Dockerfile.~
~Please don't merge.~ Maintenance page should not need `graphql` because it's never sending a backend request.
- None
=> fix: Don't attempt to save locale if not authenticated

backend/src/schema/resolvers/locations.js, backend/src/schema/resolvers/locations.spec.js
A query such as `{ notifications }` would return `null` for Locations
with a missing translation, e.g. `nameRU`. This would not happen for
queries implemented by `neo4j-graphql-js` because they nullify all
missing attributes automatically.
- None
=> fix: return `null` for missig translations

SUMMARY.md, backend/neo4j-graphql-js.md, backend/package.json, backend/src/schema/resolvers/badges.js, backend/src/schema/resolvers/posts.js, backend/src/schema/resolvers/users.js, backend/yarn.lock
I deprecated the debug flags myself here:
https://github.com/neo4j-graphql/neo4j-graphql-js/pull/288
You can now debug the queries run by `neo4j-graphql-js` by starting
the backend like this:
```bash
DEBUG=neo4j-graphql-js yarn run backend
```
- None
=> build(deps): remove deprecated debug flags

webapp/components/Editor/defaultExtensions.spec.js
Up to this point, once you've inserted a given URL to the editor, and it renders a new embeded content, if you hit Return, and try using a tag, or mention, it would not work since the paragraph was never closed.
Unless you explicitly hit return again, to escape the given text block you were in, you could not use mentions. See the PR/Issue for further info.
This PR fixes this by simply changing the call to the Embeded content, so it is not grouped as "Inline" by the editor, since if this happens, the embeded content will get inserted IN the current block.
- fixes #1937 
- fixes the required changes on #2152
=> fix(editor): Fix hashtags not working after embeded content

docker-compose.build-and-test.yml
I'm annoyed to scroll when I'm debugging the build server logs. I think,
if you run `jest` with an environment variable `CI` set to true, it will
not try to output colorized log and also does not output which test it's
currently running.
That should lead to the desired, smaller log on Travis CI.
- None
=> build: less verbose output on build server

webapp/assets/styles/main.scss, webapp/components/PostCard/PostCard.vue, webapp/graphql/Fragments.js, webapp/pages/post/_id/_slug/index.vue
Language property of post is passed to frontend. When editing post in a different locale the language does not change by default. Added language attributes to post and postcard (article element in html) to have the hyphenation corresponding to the language of the post and not to the chosen locale.
- fixes #2187
- fixes #2115
=> 2187 language does not change on edit

backend/src/schema/resolvers/user_management.js, backend/src/schema/resolvers/user_management.spec.js, webapp/components/LoginForm/LoginForm.spec.js, webapp/components/LoginForm/LoginForm.vue
I first created a frontend spec before I learned that I can (and should) normalize the email in the backend in the `login` resolver.
- fix #2329
=> 2329 normalize emails in login form

backend/src/middleware/permissionsMiddleware.js, backend/src/schema/resolvers/users.js, backend/src/schema/resolvers/users.spec.js
Ideally we would not have this inconsistent edge case that we filter
through the user type. Much better would be a graphql query like:
```graphql
{
User(filter: { primary_email: { email: "something@example.org" } }) {
id
name
slug
}
}
```
**EDIT**
I tried to implement the above behaviour and I think it's OK to have this edge case. Reason: you could nest `_UserFilter` indefinitely. So it becomes complex and risky to create a `graphql-shield` rule based on `args.filter.primary_email`.
Keeping it simple stupid and having this one inconsistency is OK I would say.
Fix #2294
=> If an admin searches for a user by email, don't crash if no user can be found

webapp/yarn.lock
- not sure why these changes were not merged in with the PR that
upgraded these packages... maybe the dependabot PR was not rebased after
merging another package bump in?? anyways, everytime I run yarn install
in webapp after pulling in the latest changes, this appears.
=> Update yarn.lock after pulling in latest changes

backend/src/middleware/notifications/notificationsMiddleware.spec.js
- the test clearly tests that the createdAt doesn't change, we changed
the implementation, but didn't change the test description
=> Update test description

webapp/nuxt.config.js, webapp/storybook/webpack.config.js
(Some of?) our browser issues in Edge and IE are caused by object spread operators, being left in the minified code after transpiling `svgs`. I could only confirm this for the `styleguide` but since using `babel-loader` alongside `vue-svg-loader` is recommended in the [official docs](https://vue-svg-loader.js.org/#configuration) it sure can't hurt.
- relates (and maybe solves) #2287
=> Use babel-loader with vue-svg-loader

backend/src/schema/resolvers/reports.js, webapp/components/features/ReportList/ReportList.story.js, webapp/components/features/ReportRow/ReportRow.vue
Return empty array instead null for "not reviewed"
@mattwr18 why did you add the null check in th resolver?
---------
Eliminate database calls for filed and reviewed
I learned map projections and list comprehensions in cypher tonight!
:tada: So much wow!
This eliminates **2n** database calls for n the number of all reports.
We could bring this to a next level by optionally matching the author (in case of a post or comment) and the post (in case of a comment), both adding another n database calls to the resolver.
**Before**
**After**
=> Eliminate database calls for reports query

webapp/pages/index.vue
Hide Donations Bar
- completes step 1 of #2401
=> Hide Donations Bar

webapp/package.json, webapp/yarn.lock
upgrades to latest styleguide version which transpiles `svgs` with `babel-loader` – this should fix at least some of the browser issues we're facing in Edge and IE
- relates (and hopefully solves) #2287
=> Bump styleguide to version 0.5.22

.travis.yml, scripts/docker_push.sh
We should have been wary after seeing the version tags in the same loop as the
`latest` tag.
This should fix our deployment in such a way that version tags are only pushed when they change and when there is no docker image already online (it should not override it).
=> Hope to fix our deployment with explicit call of `bash`

webapp/components/PostCard/PostCard.vue
@alina-beck the CSS class `.ds-card-footer` gets in the way of the
`overflow: hidden` from the styleguide. The scoping avoids the issue.
Of course this is not a great solution and the whole file needs to be
refactored and fixed. I also see a lot of `<div>`s with a style
attribute. All of that is legacy code that survived for too long.
- None
=> Show the comments again

scripts/docker_push.sh
So I had `DOCKER_CLI_EXPERIMENTAL=enabled` enabled by default and
couldn't reproduce the error on my machine. This time I'm pretty sure it
works as expected.
=> Fix docker manifest on Travis CI

webapp/components/utils/UpdateQuery.js, webapp/components/utils/UpdateQuery.spec.js, webapp/pages/index.vue, webapp/pages/profile/_id/_slug.vue
I don't know where the bug originates. But it can only be that either
`previousResult` or `fetchMore` result is sometimes undefined. This
should make the function bullet-proof for these situations.
- None
=> Fix broken scroll behaviour on index and profile page

webapp/graphql/Fragments.js, webapp/graphql/PostQuery.js, webapp/graphql/User.js
This is refactoring all our fragments and fixing the warning about an
existing name `user`. Apparently, fragments should have a unique name
globally.
I decided to call `userFragment`, `postFragment` the fragments for one
object and use different names to query for related objects.
I would be glad to learn a better way to handle this.
- None
=> Fix duplicate fragment `user` issue

webapp/components/ContributionForm/ContributionForm.spec.js, webapp/components/ContributionForm/ContributionForm.vue
- we were not setting the form.imageAspectRatio to the value of the
post's imageAspectRatio, so when a user updated their post, but did not
update their imageAspectRatio it would set it to null
@alina-beck
=> Fix imageAspectRatio set to null UpdatePost

cypress/support/commands.js
- We do not need to simulate a user closing the toaster, as this is not
that common of a user interaction, fails intermittently locally, and
costs unnecessary build time
- fixes #2775
=> fix: cypress breaks locally in login step

webapp/locales/de.json
In order to have consistency between the two language files, I removed the obsolete German keys.
Also fixes a minor spelling error.
- fixes #2528
=> fix: remove obsolete German keys

scripts/deploy.sh
=> fix: deploy script with new naming convention

backend/src/db/migrations/20200123150105-merge_duplicate_user_accounts.js
- Also, use original verifiedAt date for emails. These users only have
newly created accounts/emails because of our blunder. Their nodes
should reflect when they became members/verified their emails.
- fixes #2967
=> fix: Use original createdAt for merged users/emails

backend/package.json, backend/yarn.lock
Force update of `fs-capacitor`, see https://github.com/jaydenseric/graphql-upload/issues/170#issue-527336432
I am testing file uploads on my machine. My local `node` has version `v13.7.0`. This resolution fix does the trick for me.
=> build(deps): Node v13 compatbility

.github/ISSUE_TEMPLATE/devops_ticket.md
This does not have an issue, but I think would be an exception... I can create an issue if others think it's necessary, but I have just copied and pasted an icon to the headers of the DevOps ticket issue template, which doesn't work with `:boom:`.
This is not code that will be deployed.
=> fix: Update devops_ticket.md

webapp/.env.template, webapp/nuxt.config.js, webapp/plugins/apollo-config.js
After some intensive debugging I found out that `req` (on the server)
and `nuxtState` (on the client) have access to the configurations
changed at runtime.
How did I debug it:
```
yarn run build
env WEBSOCKET_URI=whatever yarn run start
```
I also put a `console.log` into `plugins/apollo-client.js`.
- fixes #3064
=> fix(nuxt-env): Configuration issue with websockets

backend/src/jwt/encode.js, backend/src/jwt/encode.spec.js, backend/src/schema/resolvers/user_management.spec.js
This will prevent unintentional encoding of users email addresses in the
JWT.
@steffi201028 this might be interesting for you as well.
- fix #2202
=> fix(jwt): Whitelist encoded JWT attributes

webapp/components/_new/generic/UserAvatar/UserAvatar.vue
make sure avatar image spans 100% width and height, so that the background is hidden
before:
after:
- fixes #3025
=> fix(frontend): avatar image covers full circle

backend/src/middleware/notifications/notificationsMiddleware.js, backend/src/middleware/notifications/notificationsMiddleware.spec.js
Fix #3088
Notifications not being created seems to be expected behaviour. But we never want to publish `{notificationAdded: undefined}`. This PR ensures this won't happen.
- fixes #3088 
This might also be a fix for our stalled builds as it avoids JavaScript runtime errors (?)
=> fix(subscriptions): Don't publish undefined

backend/src/db/factories.js, backend/src/models/Category.js, backend/src/models/Comment.js, backend/src/models/Donations.js, backend/src/models/Post.js, backend/src/models/Report.js, backend/src/models/SocialMedia.js, backend/src/models/User.js, backend/src/schema/resolvers/comments.js, backend/src/schema/resolvers/fileUpload/index.js, backend/src/schema/resolvers/helpers/generateNonce.js, backend/src/schema/resolvers/passwordReset.js, backend/src/schema/resolvers/posts.js
```
(node:149) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid/blob/master/README.md#upgrading-from-v3x-of-this-module for more information.
PASS src/schema/resolvers/follow.spec.js (5.295s)
(node:149) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid/blob/master/README.md#upgrading-from-v3x-of-this-module for more information.
PASS …
```
=> chore(build): Fix uuid deprecations

backend/src/schema/resolvers/passwordReset.js
- this is updating the user node, so it should update the updatedAt.
we recently ran into an issue where we weren't sure if a user had
successfully changed their password with the passwordReset, and needed
to look into it further to see if the PasswordReset had been used or not
to tell if it was successful.
=> fix: Update user.updatedAt when password is reset

backend/src/schema/resolvers/user_management.js, backend/src/schema/types/type/User.gql, webapp/graphql/User.js, webapp/store/auth.js
This is a
* small refactoring, we want to keep all graphql in the frontend under `graphql`
* performance improvement, because we don't query for expensive user counts and avoid N+1 queries
* hopefully a fix for our user who receives 504 timeout for `currentUser` query.
- fixes #3208
=> perf(neo4j): Improve currentUser read performance

webapp/components/Dropdown.vue
This change
1. calculates the width of the vertical scrollbar (_px-value_)
2. sets _px-value_ as `padding-right` to `.main-navigation` and `body`
thus preventing the page's content from shifting when filling up space that the disappearing scrollbar leaves behind.
- fixes #2607 
- relates #2564 
Remake of #3151
=> fix: layout shift [2607]

cypress/integration/common/steps.js, cypress/integration/notifications/Mentions.feature, webapp/components/NotificationMenu/NotificationMenu.spec.js, webapp/components/NotificationMenu/NotificationMenu.vue
I've tried using `filled` instead of `ghost` to make the difference in behavior clear, but that always turned out to be too aggressive/standing out, since nothing else up there has this much color/fill.
Removing the counter all together feels like a good visual cue that the behavior of the button changed.
- solves #2823
Remake of #3170
- Is there a way to test the `:to` parameter of the `<nuxt-link>`?
=> feat: zero bell to all notifications page [2823]

scripts/translations/sort.sh
The output of ./scripts/translations/sort.sh tends to get overlooked in the TravisCI logs.
This change makes the "x.json is not sorted by keys" prominent red and adds a hint to the sort.sh --fix feature.
Tests obviously fail now to show the error output. I will rebase out the 'temp:' commits, if approved.
Before:
After:
Messages in bold, --fix hint in blue - which I like better as the hint is info, not a warning and it really makes it stand out:
=> feat: more prominent output of ./scripts/translations/sort.sh

webapp/components/CommentForm/CommentForm.vue, webapp/components/ContentMenu/ContentMenu.vue, webapp/components/ContributionForm/ContributionForm.vue, webapp/components/DropdownFilter/DropdownFilter.vue, webapp/components/FilterPosts/FilterPosts.vue, webapp/components/LocaleSwitch/LocaleSwitch.vue, webapp/components/NotificationMenu/NotificationMenu.vue, webapp/components/Password/Change.vue, webapp/components/PasswordReset/ChangePassword.vue, webapp/pages/admin/categories.vue, webapp/pages/admin/hashtags.vue, webapp/pages/admin/users.vue, webapp/pages/settings/index.vue, webapp/pages/settings/my-email-address/enter-nonce.vue, webapp/pages/settings/my-email-address/index.vue, webapp/vue.md
> Following https://vuejs.org/v2/guide/components-slots.htmlNamed-Slots
We are using deprecated syntax in various places in our code base
In short, <template slot="index" slot-scope="scope"\> can be refactored to <template #index="scope"\>
Motivation for this change, and more examples can be found here https://github.com/vuejs/rfcs/blob/master/active-rfcs/0001-new-slot-syntax.md
- addresses #2117 
1. [x] use shorthand for default slots
2. [x] ~Some test failures are seemingly caused by <ds-*> not handling the new syntax well. If so, and since they are supposed to be refactored out anyway, this might be a blocker.~
Turns out, components are not the cause. Just didn't understand the new syntax, fully. ([see comment](https://github.com/Human-Connection/Human-Connection/pull/3258#issuecomment- …
=> refactor: deprecated slot syntax [2117]

backend/src/db/migrations/20200320200315-refactor_all_images_to_separate_type.js
Apparently we have posts or users which have the same `imageUrl` or `avatar`. If we create image nodes we will run into unique constraint violations when we try to create the unique index.
~When I try to `yarn run db:migrate up` on production data on my machine and in docker the migration takes way too much time.~ If you create the unique index first, it's doing fine.
- None
=> fix(migration): Avoid unique constraint violation

backend/yarn.lock, webapp/components/_new/generic/CounterIcon/CounterIcon.story.js, webapp/components/_new/generic/CounterIcon/CounterIcon.vue, webapp/components/generic/SearchPost/SearchPost.spec.js, webapp/components/generic/SearchPost/SearchPost.vue, webapp/components/generic/SearchableInput/SearchableInput.story.js
=> refactor: favor CSS over syleguide components SearchPost.vue

webapp/components/Editor/nodes/LegacyEmbed.js
[EmbedComponent](https://github.com/Human-Connection/Human-Connection/blob/fbcc10ef0d6cbca69cfc75689dfbf23103cb1d91/webapp/components/Embed/EmbedComponent.vue) is inserted as editor content (inside `<p>`) and selected with a [NodeSelection](https://prosemirror.net/docs/ref/#state.NodeSelection) @click. 
Changing the schema of the [Embed](https://github.com/Human-Connection/Human-Connection/blob/fbcc10ef0d6cbca69cfc75689dfbf23103cb1d91/webapp/components/Editor/nodes/Embed.js#L42) Node has no effect for
- `selectable: false`
- `atom: true`
- `marks: ''`
(see prosemirror [NodeSpec](https://prosemirror.net/docs/ref/#model.NodeSpec))
fbcc10e - Prevent selection in entire embed element. This has the obvious downside that no content can be selected for e.g. copying.
- …
=> fix: Text of editor embeds disappearing on click [2727]

webapp/components/Editor/ContentViewer.vue
Margin of H3 H4 HR was set to zero by reset.css. This was causing
problem in readability.
Add `margin` CSS rule to `Editor/ContentEditor.vue` component.
Before
After
- fixes #3628
=> feat: 🍰 Increase Margin Of Header And Ruler For Better Legibility

backend/src/schema/resolvers/statistics.spec.js, backend/src/schema/resolvers/users.spec.js, webapp/components/DeleteData/DeleteData.spec.js, webapp/components/DeleteData/DeleteData.vue, webapp/graphql/User.js, webapp/locales/de.json, webapp/locales/en.json
the checkboxes for saved contributions and comments of a user are displayed again at userDelete
- fixes #3498
=> fix: 🍰 Checkboxes Not Missing Anymore On Delete User Account Page

webapp/components/CommentList/CommentList.spec.js, webapp/components/CommentList/CommentList.vue
Changed the filter so that the comments that are deleted are not counted in the comment number anymore
- fixes #2112
- fixes #3357
=> fix: 🍰 Comment Counters Are Now Equal

.github/semantic.yml
- Added 'semantic.yml'.
The semantic pull request doesn’t work if there is only one commit in the PR. That sometimes happen and then the semantic-PR mechanism fail.
I can and will not do a senseless second commit in a PR …
Description how to change this is here:
https://github.com/zeke/semantic-pull-requests#configuration
- fixes #3883
=> build: Add semantic PR config

.travis.yml
Disable Codecov for last deploy.
Then we don't need the CODECOV_TOKEN on Travis.org.
- fixes #3945
=> build: 🍰 Disable Codecov for last deploy
