Human-Connection/Human-Connection

- .gitignore
- backend/src/activitypub/ActivityPub.js
- backend/src/activitypub/utils/activity.js
- backend/src/activitypub/utils/actor.js
- backend/src/activitypub/utils/collection.js
- backend/src/activitypub/utils/index.js
- backend/src/index.js
- backend/src/middleware/activityPubMiddleware.js
- backend/test/features/webfinger.feature
- webapp/nuxt.config.js
> Should fix #234 + refactor domain to hostname

- backend/package.json
- backend/src/activitypub/ActivityPub.js
> Apparently this change got overlooked

- backend/src/middleware/dateTimeMiddleware.js
- backend/src/middleware/dateTimeMiddleware.spec.js
- backend/src/middleware/includedFieldsMiddleware.js
- backend/src/middleware/index.js
- backend/src/middleware/orderByMiddleware.js
- backend/src/middleware/orderByMiddleware.spec.js
> Order all resources by createdAt descending (as default)

- backend/src/graphql-schema.js
- backend/src/middleware/index.js
- backend/src/middleware/notificationMiddleware.spec.js
- backend/src/middleware/notifications/mentions.js
- backend/src/middleware/notifications/mentions.spec.js
- backend/src/middleware/notificationsMiddleware.js
- backend/src/middleware/notificationsMiddleware.spec.js
- backend/src/middleware/permissionsMiddleware.js
- backend/src/resolvers/notifications.js
- backend/src/resolvers/notifications.spec.js
- backend/src/server.js
I basically used the auto-generated resolver and authorized it.
On a side I would suggest we should explicitly whitelist **all** new graphQL types.
- fixes #346
> Mark a notification in the backend as read

- README.md
> Fix emojis, remove duplicate link

- installation.md
cc @ulfgebhardt that was missing in the docs for you
> Add instruction to configure local cypress config

- .travis.yml
Because of: https://github.com/Human-Connection/Human-Connection/issues/470
> Disable cypress test recordings

- webapp/docker-compose.yml
Probably a left-over from the Styleguide?
> Unexpose irrelevant port 8080

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/login.vue
Work in Progress:
Localise all unlocalised texts in Webapps.
- relates #451
> [WIP] 451 lokalise unlocalised texts

- .gitignore
- .travis.yml
- README.md
- backend/package.json
- package.json
- webapp/package.json
- yarn.lock
this pull request enables jest to collect test coverage
- fixes #469
> Add test coverage

- webapp/package.json
- webapp/yarn.lock
- it introduced a bug that caused failing tests
- I have found an open issue on the repo and commented what I experienced here https://github.com/scrumpy/tiptap/issues/188#issuecomment-490532736
- fixes #572
> Revert tiptap upgrade

- CONTRIBUTING.md
Updating the CONTRIBUTING.md to include notes on how code reviews are currently done
> Update CONTRIBUTING.md with codereview notes

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- more emoji
- removed unused sections
- more meta data
- assign new issues to ulfgebhardt
- None
> 🍰 2019/kw21/github_templates_update

- webapp/pages/profile/_id/_slug.vue
Use a smaller size for avatar `<ds-avatar>`
- fixes #643
> Change ds-avatar size to x-large

- deployment/human-connection/README.md
Updates instructions on setting a local Kubernetes cluster with minikube.
> More descriptive minikube setup instructions

- backend/Dockerfile
- backend/package.json
- backend/yarn.lock
See me in action at https://nitro-production.human-connection.org/
- fix #600
> Use our own fork to workaround #600 for now

- webapp/components/Avatar/Avatar.spec.js
- webapp/components/Avatar/Avatar.vue
- webapp/components/User/index.vue
- webapp/layouts/default.vue
- webapp/pages/profile/_id/_slug.vue
Similar to the image component, create a wrapper for `ds-avatar`.
- fixes #689
> 689 fix broken image urls after upload

- webapp/components/Upload/index.vue
> Fix user avatar jumping on upload

- webapp/components/Upload/index.vue
> Add logo as default avatar background image

- webapp/components/ContentMenu.vue
- webapp/components/Modal.vue
- webapp/components/ReleaseModal/ReleaseModal.spec.js
- webapp/components/ReleaseModal/ReleaseModal.vue
- webapp/locales/de.json
- webapp/locales/en.json
> 🍰 release contribution again

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/profile/_id/_slug.vue
402-userprofile-shouted-tab - text adapted for single or multiple. / css extended.
the basis for this PR is the PR: https://github.com/Human-Connection/Human-Connection/pull/672
- relates 402
> 402 userprofile shouted tab 2

- scripts/docker_push.sh
I made two mistakes:
1. Forgot to set permissions on dockerhub (done earlier)
2. Fix the name of the docker image in the deployment script
- None
> Fix deployment - wrong docker image name

- cypress/integration/common/steps.js
- webapp/components/FilterMenu/FilterMenu.spec.js
- webapp/components/FilterMenu/FilterMenu.vue
- webapp/layouts/default.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/index.vue
> 269 filter by followed users

- webapp/components/Modal/DisableModal.spec.js
- webapp/components/Modal/DisableModal.vue
- webapp/components/ReleaseModal/ReleaseModal.spec.js
- webapp/components/ReleaseModal/ReleaseModal.vue
It might create better user experience, but for the small user group I
think the complexity is worse than the feature itself.
- None
> Disable the location.reloads

- backend/package.json
- backend/src/jwt/encode.js
- backend/yarn.lock
I have seen this PR here: https://github.com/Human-Connection/Human-Connection/pull/774 and I thought: Never saw that one before, where is it used and what is the purpose? I could find this line only and thought this is not a justification for having the package installed.
- None
> Replace dependency `ms` completely

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/profile/_id/_slug.vue
> Translate network tab on the left profile page

- .travis.yml
temporarily remove cypress record as all the builds are failing due to limit reached
> Revert changes to cypress record

- webapp/components/PostCard/index.vue
I forgot the most important part: Proxy teaser image urls.
Fix #820 finally
- None
> Follow up on #820

- webapp/components/ContributionForm/index.vue
> Add placeholder for new contributions

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/locales/es.json
- webapp/locales/fr.json
Los paquetes de idioma español y francés están actualizados. 
- fixes #764 
Which language do we use as a reference? 
I would suggest German.
> [Bug] Untranslated Texts in Post Page #764

- webapp/components/FilterMenu/FilterMenu.vue
- webapp/locales/de.json
- webapp/locales/en.json
eine Textbeschreibung für die Filterblase 
- fixes https://github.com/Human-Connection/Human-Connection/issues/849
> Fix a text description for the filter bubble

- webapp/components/comments/CommentList/CommentList.spec.js
- webapp/components/comments/CommentList/index.vue
- webapp/pages/post/_id.vue
When you call up a post you can scroll to the comments. 
Whether a comment is already written or not.
- fixes #436
- None
> When you call up a post you can scroll to the comments

- webapp/components/FilterMenu/FilterMenu.spec.js
I see our `master` is broken, so I'll try to fix it.
- None
> Fix master build

- webapp/components/DeleteData/DeleteData.vue
- Thanks @Tirokk for pointing this out. How was this even working before?
- fixes #867
> Add enableDeletionValue to unlock deletion

- backend/Dockerfile
- backend/package.json
- backend/src/seed/factories/posts.js
- backend/src/seed/seed-db.js
- backend/yarn.lock
- cypress/integration/common/steps.js
- cypress/integration/post/WritePost.feature
- package.json
- webapp/components/Avatar/Avatar.spec.js
- yarn.lock
> Fix failing build due to lorempixel.com being down

- SUMMARY.md
- deployment/digital-ocean/https/templates/ingress.template.yaml
- deployment/human-connection/mailserver/README.md
- deployment/human-connection/mailserver/deployment-mailserver.yaml
- deployment/human-connection/mailserver/service-mailserver.yaml
- deployment/human-connection/templates/configmap.template.yaml
Why not deploying a dummy mailserver? It's already deployed [here](https://nitro-mailserver.human-connection.org/#/) this PR will add documentation.
- None
> Deploy development mailserver

- webapp/components/ContributionForm/ContributionForm.spec.js
- webapp/components/ContributionForm/index.vue
> Write tests for UpdatePost, refactor tests

- backend/src/schema/resolvers/users.spec.js
- backend/src/schema/types/schema.gql
- webapp/components/DeleteData/DeleteData.vue
@mattwr18 this patches the vulnerability. However we should never do
string interpolation with user input.
- None
> Patch cypher injection vulnerability

- webapp/components/SearchInput.vue
- webapp/layouts/default.vue
the menu is adapted to the styleguide of HC. Responsive. Not yet perfect, but better than before. 
the search was adapted for mobile
- fixes #https://github.com/Human-Connection/Human-Connection/issues/907
> 907 mobile responsive menu navbar

- webapp/graphql/PostQuery.js
- webapp/pages/post/_id/_slug/index.vue
> Refactor code to extract query to it's own file

- backend/src/schema/types/schema.gql
> Remove unused query as cleanup

- webapp/layouts/default.vue
long links and long related content is broken up
- fixes https://github.com/Human-Connection/Human-Connection/issues/716
> long links and content is wrapped

- webapp/graphql/PostMutations.js
- we do not need to request it and if there is none it throws an error
- fixes #965 
I wanted to cypress test the `DeleteData` functionality, but I believe you said not to @roschaefer because the tests are expensive(time-consuming)... maybe we can talk about it in a meeting(?)
> Remove request for image in UpdatePost mutation from UI

- backend/src/bootstrap/neode.js
- backend/src/models/EmailAddress.js
- backend/src/models/InvitationCode.js
- backend/src/models/User.js
- backend/src/models/User.spec.js
- backend/src/models/index.js
- backend/src/models/spec/User.spec.js
- backend/src/schema/types/type/User.gql
While implementing the signup I discovered this bug. Fortunately, we don't face it until we start to create user accounts.
Includes a refactoring, too.
- None
> User role not nullable

- cypress/integration/common/steps.js
- webapp/components/Password/Change.spec.js
- webapp/components/Password/Change.vue
- webapp/components/PasswordReset/ChangePassword.spec.js
- webapp/components/PasswordReset/ChangePassword.vue
- webapp/components/Registration/CreateUserAccount.spec.js
- webapp/components/Registration/CreateUserAccount.vue
- webapp/components/Registration/Signup.spec.js
- webapp/components/Registration/Signup.vue
- webapp/components/utils/PasswordFormHelper.js
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/nuxt.config.js
- webapp/pages/admin.vue
- webapp/pages/admin/invite.vue
- webapp/pages/login.vue
- webapp/pages/registration.vue
- webapp/pages/registration/create-user-account.vue
This should enable admins to invite users by email address. It works just as a normal signup by email, except that it's only allowed for admins.
- close #420
> Signup new users as admin

- deployment/legacy-migration/maintenance-worker/migration/neo4j/users/users.cql
@mattwr18 assumptions were correct, it's just this line to fix the data import.
- None
> Fix regression of data import

- webapp/locales/en.json
the imprint was taken over like from the Alpha, in german and english
- fixes #1003
> Created imprint page, added English translations

- webapp/components/ContributionForm/ContributionForm.vue
Add Author details including last active to the contribution form
- None
> Add details to contribution form

- webapp/components/ContributionForm/ContributionForm.spec.js
@mattwr18 you added `currentUser` in 19b2b7a49 without running the tests,
didn't you?
- None
> Fix console.errors during `yarn run test`

- webapp/pages/profile/_id/_slug.vue
Some small thing I noticed giving a `PR` review for @alina-beck
> Use a link's username, open separate window on click

- .travis.yml
> seed first and then reset

- webapp/layouts/default.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/code-of-conduct.vue
add page code-of-conduct, english and german
- fixes #1005
> add page code-of-conduct, english and german

- webapp/layouts/default.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/locales/es.json
- webapp/locales/fr.json
- webapp/locales/it.json
- webapp/locales/nl.json
- webapp/locales/pl.json
- webapp/locales/pt.json
- webapp/nuxt.config.js
- webapp/pages/data-privacy.vue
- webapp/pages/login.vue
- webapp/pages/logout.vue
edit layout default for guests
> edit layout default for guests

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/terms-and-conditions.vue
Fix terms and conditions template, english and german
- fixes #1002
> Fix terms and conditions template, english and german

- webapp/nuxt.config.js
- webapp/package.json
I couldn't see any difference in using `transition`, `pageTransition` or
neither of those, so I decided to disable the configuration completely.
- None
> Fix depreciation warnings

- webapp/locales/pl.json
> polish locales

- backend/src/seed/seed-db.js
> Add data-mention-id to seeds mentions

- README.md
> Fix expired discord link

- webapp/locales/de.json
- webapp/locales/en.json
We agreed to capitalize the first word and use lowercase for subsequent words.
Also, we are using an exclamation mark on successful actions. I did not add it for `registration.signup.form.success` cause it felt strange adding an exclamation mark just informing the user an email was sent.
- None
> Maintain consistent naming/punctuation conventions

- deployment/legacy-migration/maintenance-worker/migration/neo4j/users/users.cql
Apparently some of our users in production have no slug, this will
assign an (hopefully unique) random slug to them.
- None
> Fix user mention menu on production data

- webapp/package.json
- webapp/yarn.lock
- Upgrading breaks our logut/login flow
- see
https://github.com/nuxt-community/apollo-module/releases
https://github.com/nuxt-community/apollo-module/pull/242/files
- fixes #1221
> Downgrade @nuxtjs/apollo

- webapp/components/MasonryGrid/MasonryGrid.spec.js
- webapp/components/MasonryGrid/MasonryGridItem.spec.js
- localVue.use(Styleguide) to register components
- find masonryGrid and emit event
- Co-authored-by: Alina Beck <alina.beck@mail.com>
- Co-authored-by: Joseph Ngugi <jngugi88@gmail.com>
> Fix vue warnings for MasonryGrid/MasonGridItem

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/index.vue
This is one of the bugs/improvements suggested by @ulfgebhardt.
- None
> Visual feedback if filters lead to 0 results

- webapp/graphql/User.js
> Fix post count always showing 0

- webapp/components/FilterPosts/FilterPosts.spec.js
- webapp/components/FilterPosts/FilterPosts.vue
- webapp/layouts/default.vue
- webapp/store/postsFilter.js
- webapp/store/postsFilter.spec.js
> Implement visual feedback if filter is active

- webapp/package.json
- webapp/yarn.lock
See https://github.com/arthurvasconcelos/vue-izitoast/pull/20#issuecomment-524131102
- None
> Update vue-izitoast after they released v1.2.0!

- backend/src/middleware/index.js
> Use ES6 syntax to avoid repetition

- webapp/components/Registration/Signup.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/admin/invite.vue
- webapp/pages/profile/_id/_slug.vue
> 🍰 454 Lokalise unlocalised texts and fixes texts

- webapp/pages/profile/_id/_slug.vue
> Fix flickering create-button

- webapp/pages/index.vue
- webapp/pages/profile/_id/_slug.vue
The infinite loading component was indeed loading infinitely.
- None
> Fix infinite-loading infinitely loading

- webapp/components/Editor/Editor.spec.js
- webapp/components/Editor/Editor.vue
> Limit suggestions list to 15, add component tests

- backend/src/schema/resolvers/user_management.spec.js
That should fix our build server.
- None
> Encode the bearer token instead of hard-coding it

- backend/src/schema/resolvers/users.js
- backend/yarn.lock
Fix that :hankey: :point_down: 
- None
> If TAC version is missing, return `null`

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/index.vue
Sadly, I think this the only way for now. As I explained in
https://github.com/Human-Connection/Human-Connection/issues/1272#issuecomment-527864948
I think we cannot do anything about it on our side for now.
- fix #1272
> Remove slow sorting options

- deployment/legacy-migration/maintenance-worker.yaml
- deployment/legacy-migration/maintenance-worker/migration/mongo/.env
> Update maintenace worker image

- webapp/components/PageFooter/PageFooter.vue
- webapp/layouts/default.vue
- moved footer styles into footer component 
- added shadow to footer
- fixes #1206
> Improve footer styling

- webapp/graphql/admin/Statistics.js
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/admin/index.spec.js
- webapp/pages/admin/index.vue
> 1487 fix admin page

- webapp/components/ContributionForm/ContributionForm.vue
- webapp/components/TeaserImage/TeaserImage.vue
- webapp/pages/post/create.vue
- depending on the size of the image, the preview looked really blurry
Also, the preview image differed from the image on the PostCard
- fixes #1199 
before `PR`
after `PR`
PostCard.vue
I also made the ContributionForm the same width as the PostCard.vue to keep them consistent
> Fix preview image craziness

- webapp/pages/profile/_id/_slug.vue
The pagination was broken when you switched tabs on the user profile.
- None
> Fix leftover of #1479

- backend/src/schema/resolvers/statistics.js
- backend/src/schema/types/schema.gql
- backend/src/schema/types/type/Statistics.gql
> Implement better statistics resolver

- backend/src/schema/resolvers/registration.spec.js
Only 7 specs left that still use GraphQLClient
- None
> Refactor registration.spec.js

- webapp/graphql/ModerationListQuery.js
- webapp/pages/moderation/index.vue
> Fix #1505 remove html

- backend/src/middleware/nodes/locations.js
- webapp/pages/settings/index.vue
@roschaefer, I was trying to get this without needing to merge into master, but I'm not sure how I can edit a file in place and restart the server... 
I was able to narrow down issue #1367 to our backend/src/middleware/nodes/locations.js
there are two places in `createOrUpdateLocations` where the error message `locationName is invalid` can possibly be called.
> Add console log for erros geolocation

- webapp/components/User/User.vue
This is a fix of e04eedf0d07ff66dba3e881e9ef8bdf5a868619e
- None
> Avatar should be centered on profile page

- webapp/pages/index.vue
Sorting dropdown is aligned with post cards
- fixes #1462
> [WIP] Sorting dropdown is aligned with post cards

- backend/src/middleware/slugifyMiddleware.spec.js
- backend/src/schema/resolvers/posts.js
- backend/src/schema/resolvers/registration.js
- backend/src/schema/resolvers/registration.spec.js
- backend/src/seed/factories/emailAddresses.js
- backend/src/seed/factories/index.js
- backend/src/seed/factories/users.js
- webapp/components/Registration/CreateUserAccount.spec.js
- webapp/components/Registration/CreateUserAccount.vue
- webapp/graphql/Registration.js
Our dear @Hardy-Peaceglobal has reported this issue. This should update the user's `about` attribute on signup.
- there is no issue for that yet
> Bugfix: `about me` not saved on signup

- deployment/legacy-migration/maintenance-worker/migration/neo4j/comments/comments.cql
> Fix import to add createdAt and updatedAt for comments

- scripts/docker_push.sh
> Fix deployment script for docker images

- webapp/components/Hashtag/Hashtag.spec.js
- webapp/components/Hashtag/Hashtag.vue
- webapp/components/Hashtag/Readme.md
- webapp/components/PostCard/index.vue
- webapp/graphql/Fragments.js
- webapp/pages/index.vue
- webapp/pages/post/_id/_slug/index.vue
- webapp/pages/post/_id/_slug/more-info.vue
- webapp/pages/profile/_id/_slug.vue
Missing translations.
Minor design changes.
Some component and file renamings.
- fixes #1501
- fixes #1502
>  🍰  Missing translations

- webapp/Dockerfile
> Fix missing images on staging

- scripts/docker_push.sh
> Fix docker image tags

- README.md
> Add CodeTriage helpers badge

- backend/src/schema/resolvers/registration.js
- backend/src/schema/resolvers/registration.spec.js
- backend/src/seed/factories/users.js
> Resend registration mail if user has not yet registered

- webapp/components/Comment.spec.js
- webapp/components/Comment.vue
- webapp/components/CommentList/CommentList.spec.js
- webapp/components/CommentList/CommentList.vue
- by passing the prop content to the content-viewer with the comments
content if it is less than 180 characters or if it's different from the
contentExcerpt
- fixes #1547
> Fix disappearing embeds on comments

- webapp/components/User/User.story.js
- webapp/components/User/User.vue
- webapp/pages/profile/_id/_slug.vue
- webapp/storybook/helpers.js
- webapp/storybook/webpack.config.js
Design Team, I need your help: Can you tell me if the datetime next to the user's slug is a problem?
- fix #1486
> 1486 make slug more usable

- webapp/components/ContributionForm/ContributionForm.vue
> Fix #1639 - No limits for post length

- backend/src/schema/resolvers/follow.js
- backend/src/schema/resolvers/follow.spec.js
- backend/src/schema/types/schema.gql
- webapp/components/FollowButton.vue
- webapp/components/User/User.vue
- webapp/graphql/User.js
- webapp/pages/profile/_id/_slug.vue
Update follow/unfollow mutation to return followed user
- relates #1583
> Improve follow/ufollow mutation

- backend/src/schema/resolvers/moderation.spec.js
Refactor tests moderation tests to use `apollo-server-testing`
- relates #1612
> 1612 refactor moderator spec

- webapp/components/Comment.vue
the comments are still strange cause they have a height of like `200px` 
maybe @alina-beck can help :pray: 
or I can keep playing...
> Fix bug where short comments scrub links

- webapp/components/Comment.vue
- this does not work with html content:
- fixes #1665
probably others
> Remove contentExcerpt from comments

- backend/src/models/User.js
- backend/src/models/User.spec.js
- cypress/integration/common/settings.js
- webapp/components/utils/UniqueSlugForm.js
- webapp/components/utils/UniqueSlugForm.spec.js
- webapp/graphql/User.js
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/package.json
- webapp/pages/settings/index.spec.js
- webapp/pages/settings/index.vue
- webapp/yarn.lock
This adds a feature to change your own slug on users settings.
- fix #1650
> Change your own slug

- webapp/components/Comment.spec.js
- webapp/components/Comment.vue
- webapp/components/CommentList/CommentList.spec.js
- webapp/package.json
- webapp/plugins/vue-filters.js
- webapp/yarn.lock
before, collpased:
uncollapsed:
after, collapsed:
uncollapsed:
> Improve comments output

- backend/src/schema/resolvers/notifications.spec.js
@mattwr18 I still see those false positives. This should fix it.
- None
> Fix intermittent backend specs

- webapp/components/Registration/CreateUserAccount.vue
I don't have time to really test this right now, feel free to do that
before merge.
- None
> Fix create account page has no logo, localisation

- webapp/components/Registration/CreateUserAccount.vue
fixes a bug introduced in #1681 
- None
> Bugfix create user page - missing submit buttons

- docker-compose.yml
Update config for neo4j running in a docker container. 
The update allows running `algo.*` and `apoc.*` queries in unrestricted mode (in dev).
- None
> update neo4j docker-compose config

- backend/src/schema/resolvers/shout.spec.js
Refactor shout spec to use `apollo-server-testing`
- None
> [WIP]1706 refactor shout spec

- backend/src/schema/resolvers/shout.spec.js
- Make clearDatabase() await
- Refactor variable declarations for reuse
- Minor refactor on readability of it blocks
> Fix failing test

- backend/src/schema/resolvers/users.js
- cypress/integration/common/report.js
- cypress/integration/common/steps.js
- cypress/integration/moderation/ReportContent.feature
- Admin/Moderators see Posts even if they are blocked
- fixes #1663
> Update Post query for blockedByUsers

- deployment/volumes/neo4j-online-backup/README.md
- docker-compose.yml
- neo4j/Dockerfile
- accept license agreement
first step to setting up online backups for our database
> Update neo4j to Enterprise edition

- backend/src/schema/resolvers/statistics.js
This is a workaround solution for counting invites for admin dashboard suggested by @roschaefer in #1633 
- fixes #1633
> fix invites count calculation for admin dashboard

- backend/src/jwt/decode.js
- backend/src/jwt/decode.spec.js
- backend/src/models/User.js
> fixes#1305 lastActiveAt

- webapp/components/Comment/Comment.vue
- webapp/components/User/User.story.js
- webapp/components/User/User.vue
- webapp/graphql/CommentMutations.js
- webapp/graphql/Fragments.js
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/locales/pt.json
- webapp/pages/post/_id/_slug/index.vue
> Show that a Post/Comment has been edited

- backend/src/middleware/email/templates/emailVerification.html
fixes a typo in our email templates: `Mlde` --> `Melde`
> Fix typo in email template

- webapp/components/ContributionForm/ContributionForm.spec.js
- webapp/components/ContributionForm/ContributionForm.vue
title character increased from 64 to 100
- fixes #1812
> Title character increased from 64 to 100

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/settings.vue
- webapp/pages/settings/embeds.vue
Remove redundancy, structure translations, remove toast success messages (update content, in this case the text and the button color).
- None
> Refactor embed settings page

- README.md
Because we are so cool! :wink: 
See: https://github.com/sourcerer-io/hall-of-fame
- None
> Add Hall of Fame to README

- backend/src/seed/seed-db.js
- webapp/pages/index.vue
- webapp/pages/profile/_id/_slug.spec.js
- webapp/pages/profile/_id/_slug.vue
- Make fetchMore orderBy equal to smart queries orderBy, 
- Make seed data more realistic,
- Avoid showing load more when there are not posts to load(less than 6 posts)
- fixes #1754
> Update profile posts apollo query

- package.json
- yarn.lock
This should fix this warning:
Please remove the change once https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/250 is resolved.
- None
> fix: security vulnerability with yarn resolutions

- webapp/locales/de.json
I have pushed a new branch with the fix.
- fixes #1874
> Fix translation error in login page

- backend/src/schema/resolvers/rewards.spec.js
Refactor rewards spec to use apollo-server-testing
- None
> 1773 refactor rewards spec

- webapp/components/Registration/CreateUserAccount.spec.js
- webapp/components/Registration/CreateUserAccount.vue
- webapp/components/Registration/Signup.vue
- webapp/locales/de.json
- webapp/locales/en.json
Confirm data privacy policy + minimum age at registration
> Confirm privacy policy minimum age at registration

- webapp/components/Registration/Signup.vue
- webapp/locales/de.json
- webapp/locales/en.json
reference to terms of use, data protection, minimum age at added  WITH CHECKBOXES
- fixes #1873
> 1873 -WITH CHECKBOX

- webapp/components/Registration/Signup.vue
- webapp/locales/de.json
- webapp/locales/en.json
reference to terms of use, data protection, minimum age at added
- fixes #1873
> 1873 -WITHOUT CHECKBOX

- webapp/components/ContributionForm/ContributionForm.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/locales/pt.json
> Add missing translations for Title placeholder

- webapp/components/TeaserImage/TeaserImage.vue
- maintain filename
- reduce image size
- fixes #1932
> Maintain filename for cropped images

- webapp/locales/de.json
> fix: typo in German translation

- backend/src/schema/resolvers/reports.js
- backend/src/schema/types/type/REPORTED.gql
- neo4j/change_report_node_to_relationship.sh
#1314  🍰 Pullrequest
Add Cypher statement for ordering.
- minor db manipulation text change
- fixes #1924
> 🍰 Add Cypher statement for ordering

- webapp/locales/en.json
> Follow @alina-beck and @Tirokk PR suggestions

- webapp/components/ContributionForm/ContributionForm.vue
Dropdown inside `HcUser` component causes vue errors in console on page reload.
Wrapping the component with `<client-only>` solves the issue.
- fixes #1311
> Fix vue errors for Contribution form

- backend/src/models/User.js
- backend/src/schema/resolvers/registration.spec.js
- backend/src/schema/types/type/EmailAddress.gql
- backend/src/schema/types/type/User.gql
- backend/src/seed/factories/users.js
- webapp/components/Registration/CreateUserAccount.spec.js
- webapp/components/Registration/CreateUserAccount.vue
- webapp/graphql/Registration.js
set language will be saved in the database of the user during registration 
eingestellte sprache wird beim registrieren in die datenbank zum user gespeichert 
#1929 
dieses Problem ist ein Teil von https://github.com/Human-Connection/Human-Connection/issues/1931
> Language will be saved in the database of the user during registration 

- webapp/pages/post/_id/_slug/index.spec.js
This fixes these console warnings :point_up:
> fix: console warnings during frontend tests

- backend/src/schema/resolvers/reports.spec.js
Refactor tests to use apollo server testing so we dont have to run the server to  run the backend tests
- None
> Refactor reports resolver spec

- webapp/plugins/vue-filters.js
> fix: Only one ellipse is displayed

- webapp/locales/de.json
Translate texts for pinning a post to German.
- fixes #1971
> 🍰 Translate texts for pinning a post to German

- webapp/components/Comment/Comment.vue
- webapp/components/CommentList/CommentList.vue
- webapp/pages/post/_id/_slug/index.vue
> Hide new CommentForm while editing a comment

- webapp/components/CommentList/CommentList.story.js
- webapp/components/LoginForm/LoginForm.story.js
- webapp/components/LoginForm/LoginForm.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/package.json
- webapp/pages/login.vue
- webapp/storybook/helpers.js
- webapp/yarn.lock
> Add storybook stories for our university students

- webapp/pages/profile/_id/_slug.vue
- clean up from pinned Posts PR
- fixes #2011
> Update fetchMore functionality on profile page

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/terms-and-conditions.vue
new terms and conditions
Nutzungsbedingungen
Die folgenden Nutzungsbedingungen sind Basis für die Nutzung unseres Netzwerkes. Beim Registrieren musst Du sie anerkennen und wir werden Dich auch später über ggf. stattfindende Änderungen informieren.
Das Human Connection Netzwerk wird in Deutschland betrieben und unterliegt daher deutschem Recht. Gerichtsstand ist Kirchheim / Teck. Zu Details schau in unser Impressum:
https://human-connection.org/impressum
Nutzung und Lizenz
Sind Inhalte, die Du bei uns einstellst, durch Rechte am geistigen Eigentum geschützt, erteilst Du uns eine nicht-exklusive, übertragbare, unterlizenzierbare und weltweite Lizenz für die Nutzung dieser Inhalte für die Bereitstellung in unserem Netzwerk. Diese Lizenz endet, sobald Du Deine Inhalte oder Deinen ganzen …
> new terms and conditions

- webapp/pages/profile/_id/_slug.vue
- we were asked to hide the shouts from other users by Dennis Hack, he
believes people will be more likely to shout a post if it is anonymous.
This only works from our UI to our backend... further steps would need
to be taken to truly make it anonymous. Also, we were asked to implement
it in such a way as to give the user the choice to show their shouts to
others.
Co-authored-by: Alina Beck <alina.beck@mail.com>
- fixes #1995
> Hide shout count on user profile unless my profile

- webapp/pages/index.vue
- Maintain consistent orderBy for fetchMore
- fixes #2022
> Remove duplicate pinned post record

- cypress/constants/terms-and-conditions-version.js
- cypress/integration/common/report.js
- cypress/integration/common/steps.js
- webapp/components/Registration/CreateUserAccount.spec.js
- webapp/constants/terms-and-conditions-version.js
- webapp/pages/terms-and-conditions.vue
New terms and conditions version 0.0.3.
Fixes the tests …
- None
> 🍰 New terms and conditions version 0.0.3

- webapp/components/PageFooter/PageFooter.vue
- webapp/locales/de.json
- webapp/locales/en.json
[Feature] Add FAQ Link to Footer feature
- fixes #2026
> add FAQ _blank-href in Footer

- webapp/locales/de.json
"Änderungen & Verlauf" zu **Änderungen**
> chnage Änderungen & Verlauf zu Änderungen

- backend/src/middleware/email/templates/wrongAccount.html
> [FIX # 2058] Typo Fixed. Password -> Passwort

- backend/src/middleware/softDelete/softDeleteMiddleware.js
deleted posts are no longer displayed in the user profile
- fixes #2063
> deleted posts no longer displayed in user profile

- webapp/components/notifications/NotificationMenu/NotificationMenu.vue
Fix: Poll Interval
- fixes #2102
> Fix: Poll Interval

- backend/src/seed/seed-db.js
- webapp/components/FilterPosts/FilterPosts.spec.js
- webapp/components/FilterPosts/FilterPosts.vue
- webapp/components/FilterPosts/LanguageFilterMenuItems.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/store/posts.js
- webapp/store/posts.spec.js
First implementation.
- fixes #2045
> 🍰 First Implementation Of Filtering Posts By Language

- .github/ISSUE_TEMPLATE/feature_request.md
Updates our Github feature template to ask for a more detailed and structured description.
I know this might be a lot, especially for people outside the core team, but maybe it's not a bad thing to make them think twice and I definitely hope it will help _us_ get better in defining features!
> Update feature template

- webapp/constants/posts.js
- webapp/layouts/default.vue
- webapp/pages/index.vue
- webapp/pages/profile/_id/_slug.vue
- webapp/store/posts.js
- on logo click
- scrollToTop
- remove duplicate records
Co-authored-by: kachulio1 <jngugi88@gmail.com>
- fixes #1994 
- fixes #2125
> Implement refresh posts, fix duplicate posts bug

- backend/src/middleware/nodes/locations.js
- backend/src/middleware/validation/validationMiddleware.js
- backend/src/schema/resolvers/comments.js
- backend/src/schema/resolvers/posts.js
We had issues with errors which we pin down to sessions that weren't closed properly. We hope this fixes it. 
- fixes #2128
> close all open sessions

- webapp/pages/login.vue
- webapp/store/auth.js
- webapp/store/auth.test.js
after successful login the saved language of the user is set
- fixes #1931
> 1931 - after successful login the saved language of the user is set

- .travis.yml
- deployment/digital-ocean/dashboard/README.md
- deployment/digital-ocean/https/README.md
- deployment/digital-ocean/https/templates/ingress.template.yaml
- deployment/human-connection/deployment-backend.yaml
- deployment/human-connection/deployment-neo4j.yaml
- deployment/human-connection/deployment-web.yaml
- deployment/human-connection/mailserver/deployment-mailserver.yaml
- deployment/human-connection/service-backend.yaml
- deployment/human-connection/service-neo4j.yaml
- deployment/human-connection/service-web.yaml
- scripts/setup_kubernetes.sh
> Update docs for deploying new server, env variables

- webapp/components/Hashtag/Hashtag.spec.js
Added `config.stubs` from provided example on issue to register the component.
- fixes #2161
> console.error in Hashtag.spec.js #2161

- scripts/setup_kubernetes.sh
- access token is ignored if any other context is passed in
> Update doctl to use default context

- webapp/components/User/User.vue
Delete Block Button in MainPage PostCards
> Fix: Delete Block Button in MainPage PostCards

- scripts/deploy.sh
fixes deploy error 
```
Error from server (NotFound): deployments.apps "nitro-backend" not found
Error from server (NotFound): deployments.apps "nitro-web" not found
```
> Update deployment names in deploy script

- webapp/pages/index.spec.js
> Added Empty Definitions For Missing Getters And Mutations

- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/settings/blocked-users.spec.js
- webapp/pages/settings/blocked-users.vue
unblock a user in the user settings
- fixes #2106
> 2106-unblock a user in the user settings

- webapp/layouts/default.vue
- webapp/nuxt.config.js
- webapp/package.json
- webapp/pages/index.spec.js
- webapp/pages/index.vue
- webapp/pages/profile/_id/_slug.spec.js
- webapp/pages/profile/_id/_slug.vue
- webapp/plugins/vue-infinite-loading.js
- webapp/plugins/vue-infinite-scroll.js
- webapp/store/posts.js
- webapp/yarn.lock
> Fix infinite scrolling out of control

- backend/.env.template
- backend/src/config/index.js
- backend/src/index.js
- deployment/human-connection/templates/configmap.template.yaml
- docker-compose.maintenance.yml
- docker-compose.yml
- package.json
If you set GRAPQHL_URI the port is already in there
As requested in #2163 I'm going to take out this code into another PR.
- None
> refactor: remove redundant port configuration

- package.json
> Helper script to install all packages

- cypress/integration/common/steps.js
- cypress/integration/notifications/Mentions.feature
- cypress/integration/post/WritePost.feature
- webapp/components/CategoriesSelect/CategoriesSelect.spec.js
- webapp/components/CategoriesSelect/CategoriesSelect.vue
- webapp/components/ContributionForm/ContributionForm.spec.js
- webapp/components/ContributionForm/ContributionForm.vue
- webapp/locales/de.json
- webapp/locales/en.json
- webapp/pages/post/edit/_id.vue
@ogerly I refactored quite a lot and I figured out how to connect individual form elements with `<ds-form>` (via `provide`) see below :point_down: 
- None
> 2119 create post consistent form input validation improvements

- webapp/components/Registration/Signup.spec.js
- webapp/components/Registration/Signup.vue
- fix #2042 Back link to login page after submitting existing email
> Fix #2042 Back Link To Login Page

- .gitignore
Added *~ (emacs backup files) to gitignore
> Add Emacs Backup Files To Gitignore (*~)

- .travis.yml
> build: record and publish all cypress test results

- .github/stale.yml
@tirokk I increased the days of inactivity to 60 and 30. You can disable
stale issues permanently by using a label "pinned".
- None
> build: configure stale bot

- webapp/components/Hashtag/Hashtag.story.js
- webapp/components/Hashtag/Readme.md
> [Systems-Development-and-Frameworks] Clickable hashtags

- webapp/locales/en.json
> Fix Typo Of Issue 2230

- cypress/integration/internationalization/Internationalization.feature
- webapp/locales/de.json
As the login-Button text in the German translation changed from "Einloggen" to "Anmelden" (which is better German) I had to change the test parameters for cypress. I do not like the design of the test, assuming something as static which obviously is not.
I hope this will let pass the pull request #2305
> Changed translation must change test :(

- README.md
> Fix incorrect link to development environment

- webapp/components/Editor/defaultExtensions.js
- webapp/components/Editor/defaultExtensions.spec.js
- webapp/components/Editor/nodes/LegacyEmbed.js
> Add LegacyEmbeds component to fix bug

- backend/src/schema/types/type/Post.gql
- we have a feature that allows users to publicly show their shouts with
their consent. we need this for the filter to work.
- fixes #2352 
@roschaefer I believe you removed this from the _PostFilter when you manually added them, but we merged in functionality that requires this filter. please review
> Add shoutedBy_some to _PostFilter

- webapp/components/TeaserImage/TeaserImage.vue
Add event modifiers stop and prevent
- fixes #2349
> Fix updating post by adding/changing image bug submits form

- backend/src/middleware/permissionsMiddleware.js
> refactor: Close session in isAuthor permission

- backend/src/schema/resolvers/emails.js
- backend/src/schema/resolvers/helpers/createPasswordReset.js
- backend/src/schema/resolvers/helpers/normalizeEmail.js
- backend/src/schema/resolvers/registration.js
- backend/src/schema/resolvers/user_management.js
- webapp/components/PasswordReset/Request.vue
- webapp/components/utils/NormalizeEmail.js
- webapp/pages/admin/users.vue
- webapp/pages/settings/my-email-address/index.vue
> Don't remove sub-addresses in emails

- docker-compose.override.yml
No public registration in development so that backend test pass
> No public registration in development so that backend test pass

- webapp/locales/de.json
Requested by @DennisHack
@Mogge are you "moriz" on our discord who keeps track of translations?
This might be interesting for you, too.
> Fix German translation of "Shouts"

- webapp/components/User/User.vue
> feat: swap user name<=>handle for discriminability

- webapp/pages/settings.vue
> Update privacy path

- backend/src/models/Report.js
- neo4j/db_manipulation/change_disabled_relationship_to_report_node.sh
- webapp/graphql/Moderation.js
- we are adding the report rule which says that if a resource was
disabled by a report with this rule, then the latest review was the one
that disabled it.
- fix db script/ add new directory for keeping record of db scripts
> Remove disable from reports.disable Query

- backend/src/schema/resolvers/reports.js
- backend/src/schema/types/type/FILED.gql
- backend/src/schema/types/type/Report.gql
- backend/src/seed/seed-db.js
- backend/yarn.lock
- webapp/components/User/User.vue
- webapp/components/features/ReportList/ReportList.vue
- webapp/components/features/ReportRow/ReportRow.vue
- webapp/graphql/Moderation.js
Co-authored-by: Tirokk <wolle.huss@pjannto.com>
- fixes #2442
> Paginate moderations page without losing filtering

- webapp/components/Registration/CreateUserAccount.spec.js
- webapp/components/Registration/CreateUserAccount.vue
- webapp/locales/de.json
- webapp/locales/en.json
- Checkbox 'no comercial account' add to creat user account
- Checkbox 'no political account' add to creat user account
- fixes #2415
> Checkbox 'no comercial + no political account' add to creat user account

- webapp/components/MasonryGrid/MasonryGridItem.spec.js
- webapp/components/MasonryGrid/MasonryGridItem.vue
- webapp/components/PostCard/PostCard.vue
- webapp/pages/index.vue
- webapp/pages/post/_id/_slug/more-info.vue
- webapp/pages/profile/_id/_slug.vue
this is a temporary rollback(?) until we can add imageAspectRatio to all Posts with an image
> Revert layout changes image aspect ratio

- webapp/pages/index.vue
- webapp/pages/profile/_id/_slug.vue
That does the job for me... Of course a test exposing the bug would be nicer.
> Fix `Cannot read 'Post' of undefined`

- backend/src/schema/resolvers/helpers/Resolver.js
- backend/src/schema/resolvers/helpers/databaseLogger.js
- backend/src/schema/resolvers/notifications.js
- backend/src/schema/resolvers/notifications.spec.js
- backend/src/schema/resolvers/reports.js
- backend/src/schema/resolvers/reports.spec.js
- webapp/graphql/Fragments.js
- webapp/graphql/PostQuery.js
- webapp/graphql/User.js
We had plenty of database calls for our notification query. That could very well be the source of our recent performance issues in the backend.
> Improve notification query performance by reducing db calls

- backend/src/schema/types/type/User.gql
third time creating this `PR` since there seems to have been an issue with github and the build was not starting
> Fix: User.name is not non-nullable

- webapp/components/ContributionForm/ContributionForm.vue
- webapp/components/Editor/Editor.vue
- webapp/package.json
- webapp/yarn.lock
This is fixing a bug where sometimes the editor would not get displayed
until you click into the title text fields. This commit also removes
some obscure optimizations.
I'm really annoyed by the cruft that we still carry around until this
very day.
Every single line of untested code, which you left because you thought:
"Well sure this is going to improve performance!" is going to bite you.
> fix: editor not visible in server-side-rendering

- webapp/components/ContentMenu/ContentMenu.spec.js
- webapp/components/ContentMenu/ContentMenu.vue
I hoped this would fix the bug with the editor sometimes not being shown
when clicking "Edit Post" but it does not.
I believe there is something with `<client-only>.
> Refactor: content menu

- webapp/components/LocaleSwitch/LocaleSwitch.vue
- webapp/graphql/User.js
> Fix maintenance service/LocaleSwitch import

- neo4j/db_manipulation/add_image_aspect_ratio.sh
- webapp/components/MasonryGrid/MasonryGridItem.spec.js
- webapp/components/MasonryGrid/MasonryGridItem.vue
- webapp/components/PostCard/PostCard.vue
- webapp/pages/index.vue
- webapp/pages/post/_id/_slug/more-info.vue
- webapp/pages/profile/_id/_slug.vue
- we had removed these changes till we could deploy them by themselves
and run the db_manipulation
-  fixes #2543
> Add back layout changes/update db_manipulation

- webapp/graphql/Fragments.js
> Fixes 2603

- webapp/components/Category/index.vue
- webapp/pages/post/_id/_slug/index.vue
Added a `ds-tag` which displays `post.language` , `v-if` the post has a language. Added style to float right.
On local:
- fixes #2239
> 🍰 Added Language Tag For Posts

- backend/src/middleware/index.js
> Parse xss before extracting mentions/hashtags

- webapp/locales/de.json
- webapp/locales/en.json
> Changes Text For SignUp

- backend/Dockerfile
- webapp/Dockerfile
- webapp/Dockerfile.maintenance
- webapp/components/DonationInfo/DonationInfo.spec.js
> Use node LTS in production

- backend/yarn.lock
> Update yarn.lock after dependabot update

- .github/stale.yml
The justification for this is that we keep an eye on those issues for
which we offer a bounty.
- None
> Issues marked as bounty never become stale

- backend/package.json
- backend/src/config/index.js
- backend/src/models/Badge.js
- backend/src/models/Category.js
- backend/src/models/Comment.js
- backend/src/models/Donations.js
- backend/src/models/EmailAddress.js
- backend/src/models/InvitationCode.js
- backend/src/models/Location.js
- backend/src/models/Post.js
- backend/src/models/Report.js
- backend/src/models/SocialMedia.js
- backend/src/models/Tag.js
- backend/src/models/UnverifiedEmailAddress.js
- backend/src/models/User.js
- backend/src/models/index.js
- backend/src/schema/types/index.js
- backend/src/seed/factories/index.js
- backend/src/server.js
- cypress/plugins/index.js
- cypress/support/factories.js
* DRY schema stitching code
* Use same `.env` configuration file for cypress tests
That last part I couldn't improve a lot. I thought it might be possible
with cypress to import all files from a folder. But since it must be
browser compatible and our backend is not using webpack or anything,
it remains a goal unreached.
- close #2773
- close #2774
> refactor(modules): Various import fixes

- webapp/components/AvatarMenu/AvatarMenu.vue
- webapp/components/PostCard/PostCard.vue
- webapp/components/UserTeaser/UserTeaser.vue
- webapp/components/_new/generic/UserAvatar/UserAvatar.vue
fixes some small issues @mattwr18, @Tirokk and I found with the new `UserAvatar` and `UserTeaser` that we had simply overlooked in the `migrate avatar PR` (#2700).
> fix(webapp): 🐛 Adjust Avatar Sizes and 'z-index'

- backend/src/db/migrate/template.js
- backend/src/db/migrations/20200127110135-create_muted_relationship_between_existing_blocked_relationships.js
- backend/src/models/User.js
> fix(backend): Add migration for muted relationship

- CONTRIBUTING.md
- README.md
This should make our open-source bounty program official!
> docs(CONTRIBUTING): Add open-source bounty program

- .github/ISSUE_TEMPLATE/refactor_tickets.md
- We want to have an issue created for each PR merged in, sometimes we
are just refactoring deprecated or legacy code and there should be an
option to create these tickets.
- fixes #2980
> chore: Add issue template for Refactoring tickets

- .github/ISSUE_TEMPLATE/devops_ticket.md
> chore: Add DevOps issue template

- backend/src/server.js
- The default limit is only 100kb
- we are getting many requests that exceed this limit
- not sure about what would be an appropriate limit, but have seen 50mb
in many examples.
- fixes #3036
> fix: Increase body parser limit

- cypress/integration/administration/TagsAndCategories.feature
- cypress/integration/common/report.js
- cypress/integration/common/steps.js
- cypress/integration/moderation/ReportContent.feature
- cypress/integration/notifications/Mentions.feature
- cypress/integration/user_account/ChangePassword.feature
- cypress/integration/user_account/Login.feature
- cypress/plugins/index.js
- cypress/support/commands.js
- package.json
- yarn.lock
> refactor(cypress): Speed up builds, avoid login through UI

- backend/src/db/seed.js
- cypress/integration/common/report.js
- cypress/integration/common/steps.js
- cypress/support/commands.js
- cypress/support/factories.js
We don't know exactly what we're doing but we'll keep this PR to trigger a couple of builds. Hopefully we get to the bottom of the problem
Recent intermittently failing tests on our build server.
Confirm it's actually fixing something by e.g. explaining the cause of the problem
> build: Fix intermittent failing tests

- cypress/integration/common/steps.js
If that's the reason for our hanging cypress tests I kill myself (metaphorically).
- None
> chore(cypress): Remove debug statements

- webapp/components/CommentList/CommentList.vue
- webapp/pages/post/_id/_slug/index.spec.js
- webapp/pages/post/_id/_slug/index.vue
Seems there was a nullpointer issue with `!post.author.blocked`.
- fix #2985
> fix(frontend): Post page won't crash on anonymous user

- webapp/components/UserTeaser/UserTeaser.vue
> fix(frontend): Remove Hover Menu from User Teaser

- cypress/integration/notifications/Mentions.feature
- package.json
- yarn.lock
- possibly related to this issue, and removes duplication https://github.com/cypress-io/cypress/issues/5139
- fixes #3117
> fix(cypress): Upgrade cypress, remove log out step

- backend/src/middleware/slugifyMiddleware.spec.js
- backend/src/models/User.spec.js
New Link, Learn how to setup the database
> docs(setup): Fix links in tests

- webapp/assets/_new/styles/tokens.scss
- webapp/components/Ribbon/index.vue
refactor and fix ribbon CSS
- fixes #3141
> fix(webapp): remove ribbon z-index

- webapp/README.md
Added docs for the locales script in the webapp/README.md
> feat: Documentation for locales script

- .travis.yml
> chore: Dockerfile/Travis node versions match

- .travis.yml
See: https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
- None
> chore(ci): Follow cypress docs to cache libraries

- backend/src/schema/resolvers/searches.js
- backend/src/schema/resolvers/searches.spec.js
- backend/src/schema/resolvers/searches/queryString.js
- backend/src/schema/resolvers/searches/queryString.spec.js
- cypress/integration/common/search.js
- cypress/integration/search/Search.feature
This. Adding specs for searches in Backand and improve the search queries
- fixes #2798 
- fixes  #2799
> feat: Specs For Searches

- backend/src/db/migrations/20200207080200-fulltext_index_for_tags.js
- backend/src/db/migrations/20200213230248-add_unique_index_to_image_url.js
- backend/src/db/migrations/20200326160326-remove_dangling_image_urls.js
As discussed in https://github.com/Human-Connection/Human-Connection/pull/3262#discussion_r398634249 we would like to remove dangling urls.
- None
> Remove dangling image urls

- backend/src/db/migrations/20200312140328-bulk_upload_to_s3.js
Did not create an issue for this, but I can, if you all want.
> fix(migration): Set maxSockets to avoid rate limit

- backend/src/schema/resolvers/searches.spec.js
> refactor(tests): return errors

- deployment/digital-ocean/README.md
> chore: Update docs for spaces backups

- webapp/testing.md
Fixed wrong unit test command. Should be 'test' instead of 'run'.
- fixes #3566
> fix: Fixed webapp unit test command.

- webapp/components/Embed/EmbedComponent.vue
- webapp/locales/de.json
- webapp/locales/en.json
Updated Buttons Styles.
Changed Order of the button.
Updated i18n.
fixes #3657 
Redesign data-privacy-warning
> feat: 🍰 Redesign Data Privacy Warning Box

- .travis.yml
Disable full stack tests only for the last deployment, because of flakiness.
- fixes #3934
> build: 💥 Disable full stack tests

- .travis.yml
Disable full stack tests only for the last deployment, because of flakiness.
BUT …
Deployment to develop is not working …
- fixes #3934
> build: 💥 Disable full stack tests, Fix deployment to develop, tryout

- backend/src/schema/resolvers/userData.js
- webapp/pages/settings/data-download.vue
fetchPolicy added to apollo for userData.
posts that are disbaled or deleted are not available for download.
Clicking on an post title to download image opens new tab for the image.
> feat: Export User Data Update

- backend/src/schema/resolvers/userData.js
- backend/src/schema/resolvers/userData.spec.js
- webapp/pages/settings/data-download.vue
spinner added to download button, only the posts written by the user are exported
> feat: Improved Data Export

- backend/Dockerfile
- webapp/Dockerfile
- webapp/Dockerfile.maintenance
Fixate the node version to '12.19.0-alpine3.10’.
- fixes #3990
> chore: 🍰 Fixate The Node Version To '12.19.0-alpine3.10'

- backend/src/schema/resolvers/userData.js
Add posts where the user has written on.
- fixes #3992
> feat: 🍰 Add Posts Where The User Has Written On
